// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// Port port object
// swagger:model Port
type Port struct {

	// alias
	Alias []string `json:"alias"`

	// port city
	City string `json:"city,omitempty"`

	// port country
	Code string `json:"code,omitempty"`

	// port coordinates
	Coordinates []float64 `json:"coordinates"`

	// port country
	Country string `json:"country,omitempty"`

	// port name
	Name string `json:"name,omitempty"`

	// port province
	Province string `json:"province,omitempty"`

	// regions
	Regions []string `json:"regions"`

	// port timezone
	Timezone string `json:"timezone,omitempty"`

	// unlocs
	Unlocs []string `json:"unlocs"`
}

// Validate validates this port
func (m *Port) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Port) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Port) UnmarshalBinary(b []byte) error {
	var res Port
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
