required = [
    "github.com/go-swagger/go-swagger/cmd/swagger",
    "github.com/fvrepo/port-domain/pkg/grpcapi/port",
    "github.com/golangci/golangci-lint/cmd/golangci-lint",
    "github.com/vektra/mockery/cmd/mockery",
]

[[constraint]]
  branch = "master"
  name = "github.com/golangci/golangci-lint"

[[override]]
  version = "v0.17.0"
  name = "github.com/go-swagger/go-swagger"

[prune]
  go-tests = true
  unused-packages = true