// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/client-api/internal/server/models"
)

// PostPortsOKCode is the HTTP code returned for type PostPortsOK
const PostPortsOKCode int = 200

/*PostPortsOK OK

swagger:response postPortsOK
*/
type PostPortsOK struct {
}

// NewPostPortsOK creates PostPortsOK with default headers values
func NewPostPortsOK() *PostPortsOK {

	return &PostPortsOK{}
}

// WriteResponse to the client
func (o *PostPortsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PostPortsBadRequestCode is the HTTP code returned for type PostPortsBadRequest
const PostPortsBadRequestCode int = 400

/*PostPortsBadRequest Bad Argument

swagger:response postPortsBadRequest
*/
type PostPortsBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostPortsBadRequest creates PostPortsBadRequest with default headers values
func NewPostPortsBadRequest() *PostPortsBadRequest {

	return &PostPortsBadRequest{}
}

// WithPayload adds the payload to the post ports bad request response
func (o *PostPortsBadRequest) WithPayload(payload *models.Error) *PostPortsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post ports bad request response
func (o *PostPortsBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostPortsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostPortsInternalServerErrorCode is the HTTP code returned for type PostPortsInternalServerError
const PostPortsInternalServerErrorCode int = 500

/*PostPortsInternalServerError General server error

swagger:response postPortsInternalServerError
*/
type PostPortsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostPortsInternalServerError creates PostPortsInternalServerError with default headers values
func NewPostPortsInternalServerError() *PostPortsInternalServerError {

	return &PostPortsInternalServerError{}
}

// WithPayload adds the payload to the post ports internal server error response
func (o *PostPortsInternalServerError) WithPayload(payload *models.Error) *PostPortsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post ports internal server error response
func (o *PostPortsInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostPortsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
