// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostPortsHandlerFunc turns a function with the right signature into a post ports handler
type PostPortsHandlerFunc func(PostPortsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostPortsHandlerFunc) Handle(params PostPortsParams) middleware.Responder {
	return fn(params)
}

// PostPortsHandler interface for that can handle valid post ports params
type PostPortsHandler interface {
	Handle(PostPortsParams) middleware.Responder
}

// NewPostPorts creates a new http.Handler for the post ports operation
func NewPostPorts(ctx *middleware.Context, handler PostPortsHandler) *PostPorts {
	return &PostPorts{Context: ctx, Handler: handler}
}

/*PostPorts swagger:route POST /ports postPorts

post ports

*/
type PostPorts struct {
	Context *middleware.Context
	Handler PostPortsHandler
}

func (o *PostPorts) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostPortsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
