// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Client API

    Schemes:
      http
    Host: localhost
    BasePath: /api/v1.0
    Version: 1.0

    Consumes:
    - multipart/form-data

    Produces:
    - application/json

swagger:meta
*/
package restapi
